### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by alexqrid** [bnb-chain/bsc-snapshots#183]
Everytime I try to download the archive after a few minutes of downloading it crashes with the following error: `2022-10-12 16:11:14 (15.9 MB/s) - Read error at byte 45460877312/809331052544 (The TLS connection was non-properly terminated.). Retrying.`
And after this error download can not be resumed.
![image](https://user-images.githubusercontent.com/30272185/195521838-b62dbb15-aaee-44ed-ba6d-43b34bd1d1cb.png)

**Comment by antoni7654** [comment]
same here. the same error with the same file trying to resume download.

**Comment by alexqrid** [comment]
Hey @antoni7654 try to use aria2c, I could download the snapshot with aria2c, it failed on 70% of the download, but after restart it continued and successfully downloaded the snapshot.
  But be sure to limit the download speed, because I tried to download it on my server with 1 Gbps, and `aria2c` utilized all the network, so my other services on the server couldn't almost work.
Just start it with the following flags `aria2c -s2 -x2 -u50M ----max-overall-upload-limit=50M ...`

**Comment by antoni7654** [comment]
Hi @alexqrid: I could download 100% of the erigon snapshot using the flags you wrote. But when I try to unpack the file with:

tar -I lz4 -xvf erigon.tar.lz4

It gives me this error:

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

Could you unpack the file? Thanks.

**Comment by alexqrid** [comment]
yes, I could unpack it without any problems
