### ISSUE TITLE
feature: consider replace the snapshot file download by Bittorent?

### ISSUE THREAD

**Issue by brilliant-lx** [bnb-chain/bsc-snapshots#216]

**Comment by du5** [comment]
If no one helps to seed or share, it would be a significant financial burden for the team because the upstream traffic of some data centers needs to be charged.

Secondly, if there are too many downloaders and too few sharers, the owner will experience significant pressure (in terms of disk usage, CPU, and bandwidth).

If participates in seed preservation, it means that additional storage space of the users will be occupied.
