### ISSUE TITLE
Geth snapshot link is broken: expired certificate

### ISSUE THREAD

**Issue by fmira21** [bnb-chain/bsc-snapshots#241]
Hi guys!

https://pub-c0627345c16f47ab858c9469133073a8.r2.dev/geth-20230409.tar.lz4

Looks like it's impossible to download the latest snapshot via this link. Aria2c cannot verify the TLS certificate.
Can you please fix this?

Thank you in advance!

**Comment by deepcrazy** [comment]
Hi there, It seems like issue is probably on your end (maybe because of different location). However, I checked and it is working fine for me (attached sc)
<img width="453" alt="image" src="https://user-images.githubusercontent.com/12941863/233193407-c867ec11-f3c4-4d10-93ed-13a4ea67fb20.png">


I would suggest to try out these solutions: 
- https://github.com/aria2/aria2/issues/1636#issuecomment-790042543
- OR add `--check-certificate=false` in your aria2c command (however, this is just a workaround)
- OR https://github.com/aria2/aria2/issues/1636#issuecomment-813364636
Thanks.
