### ISSUE TITLE
latest snapshots corrupted

### ISSUE THREAD

**Issue by rotarur** [bnb-chain/bsc-snapshots#360]
I downloaded the latest snapshots as described in the documentation:
```
https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240520.lz4.000
https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240520.lz4.001
https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240520.lz4.002
https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240520.lz4.003
https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240520.lz4.004
https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240520.lz4.005
https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240520.lz4.006
https://pub-60a193f9bd504900a520f4f260497d1c.r2.dev/erigon_data_20240520.lz4.007
```

but with these my node is not syncing at all and for a few days is showing the same log:
```
[INFO] [06-08|17:11:46.316] [parlia] snapshots build, gather headers block=38800000
[INFO] [06-08|17:11:46.475] [parlia] snapshots build, gather headers block=38800000
[INFO] [06-08|17:11:46.618] [parlia] snapshots build, gather headers block=38800000
```

I also tried to unwind 10 blocks but then again it blocked on another block.

if I start the node without the snapshots It's syncing fine

```
[INFO] [06-08|23:08:47.656] [parlia] snapshots build, gather headers block=2800000
[INFO] [06-08|23:08:47.656] [parlia] snapshots build, recover from headers block=2800000
[INFO] [06-08|23:08:49.031] [2/15 Headers] Inserting headers         progress=2812011 queue=1
[INFO] [06-08|23:09:19.030] [2/15 Headers] Wrote block headers       number=2896826 blk/second=6175.733 alloc=1.6GB sys=2.7GB invalidHeaders=0 rejectedBadHeaders=0
[INFO] [06-08|23:09:22.918] [parlia] snapshots build, gather headers block=2900000
[INFO] [06-08|23:09:22.918] [parlia] snapshots build, recover from headers block=2900000
[INFO] [06-08|23:09:49.031] [2/15 Headers] Wrote block headers       number=2962251 blk/second=2180.833 alloc=2.6GB sys=2.8GB invalidHeaders=0 rejectedBadHeaders=0
[INFO] [06-08|23:10:03.169] [parlia] snapshots build, gather headers block=3000000
[INFO] [06-08|23:10:03.169] [parlia] snapshots build, recover from headers block=3000000
[INFO] [06-08|23:10:19.031] [2/15 Headers] Wrote block headers       number=3072836 blk/second=3686.167 alloc=2.2GB sys=2.9GB invalidHeaders=0 rejectedBadHeaders=0
[INFO] [06-08|23:10:35.325] [parlia] snapshots build, gather headers block=3100000
[INFO] [06-08|23:10:35.325] [parlia] snapshots build, recover from headers block=3100000
[INFO] [06-08|23:10:49.030] [2/15 Headers] Inserting headers         progress=3135082 queue=1
[INFO] [06-08|23:11:10.590] [parlia] snapshots build, gather headers block=3200000
[INFO] [06-08|23:11:10.590] [parlia] snapshots build, recover from headers block=3200000
[INFO] [06-08|23:11:18.781] [p2p] GoodPeers                          eth68=33
[INFO] [06-08|23:11:18.812] [mem] memory stats                       Rss=4.7GB Size=0B Pss=4.7GB SharedClean=4.0KB SharedDirty=0B PrivateClean=1.1GB PrivateDirty=3.7GB Referenced=4.7GB Anonymous=3.7GB Swap=0B alloc=1.6GB sys=3.1GB
[INFO] [06-08|23:11:19.008] [txpool] stat                            pending=0 baseFee=0 queued=8 alloc=1.6GB sys=3.1GB
[INFO] [06-08|23:11:19.031] [2/15 Headers] Wrote block headers       number=3218545 blk/second=4856.967 alloc=1.6GB sys=3.1GB invalidHeaders=0 rejectedBadHeaders=0
[INFO] [06-08|23:11:48.572] [parlia] snapshots build, gather headers block=3300000
[INFO] [06-08|23:11:48.572] [parlia] snapshots build, recover from headers block=3300000
[INFO] [06-08|23:11:49.031] [2/15 Headers] Wrote block headers       number=3303077 blk/second=2817.733 alloc=2.1GB sys=3.1GB invalidHeaders=0 rejectedBadHeaders=0
[INFO] [06-08|23:12:18.970] [parlia] snapshots build, gather headers block=3400000
[INFO] [06-08|23:12:18.971] [parlia] snapshots build, recover from headers block=3400000
[INFO] [06-08|23:12:19.031] [2/15 Headers] Inserting headers         progress=3400506 queue=1
```

**Comment by houkan** [comment]
i got totally same issue here.  what can we do now ?  waiting for new snapshots files. or .do we can use previous snapshots ?

**Comment by STdevK** [comment]
The team is checking on the snapshot

**Comment by rotarur** [comment]
I'm using the latest version of erigon

```
ghcr.io/node-real/bsc-erigon:1.2.9
```

with these arguments:
```
          - --chain=bsc
          - --datadir=/bsc
          - --healthcheck
          - --http
          - --http.addr=0.0.0.0
          - --http.port=8545
          - --http.compression
          - --http.vhosts=*
          - --http.corsdomain=*
          - --http.api=eth,debug,net,trace,web3,erigon
          - --private.api.addr=0.0.0.0:9090
          - --ws
          - --ws.compression
          - --metrics
          - --metrics.addr=0.0.0.0
          - --metrics.port=6060
          - --torrent.download.rate=256mb
          - --rpc.returndata.limit=1000000
          - --db.pagesize=16kb
          - --db.size.limit=12TB
          - --p2p.protocol=68
          - --log.console.verbosity=dbug
          - --snapshots=true
```

I'm running the erigon in k3s cluster

**Comment by htkcodes** [comment]
this fixed?

**Comment by rotarur** [comment]
not yet, we're waiting for the team to check the snapshots. any updates here @STdevK ?

**Comment by houkan** [comment]
am try to fix the snapshot run a command 

after reset_state procceing like 20hours,  still haven't fix the problem.


`integration reset_state  --datadir ./data --chain bsc &`

and logs end like this


[INFO] [06-11|22:39:27.720] Progress: TransactionLog 99.86%
[INFO] [06-11|22:39:47.720] Progress: TransactionLog 99.88%
[INFO] [06-11|22:40:07.720] Progress: TransactionLog 99.90%
[INFO] [06-11|22:40:27.720] Progress: TransactionLog 99.93%
[INFO] [06-11|22:40:47.720] Progress: TransactionLog 99.95%
[INFO] [06-11|22:41:07.720] Progress: TransactionLog 99.97%
[INFO] [06-11|22:41:27.720] Progress: TransactionLog 99.99%
[INFO] [06-11|22:42:21.632] [mem] memory stats                       Rss=453.2GB Size=0B Pss=453.2GB SharedClean=4.0MB SharedDirty=0B PrivateClean=452.1GB PrivateDirty=1.1GB Referenced=452.8GB Anonymous=1.1GB Swap=0B alloc=28.5MB sys=136.9MB
[INFO] [06-11|22:43:05.794] Clear                                    table=CallTraceSet
After reset:
Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

stage_at        prune_at
Snapshots                        38874989        0
Headers                          38874910        0
BorHeimdall                      0               0
BlockHashes                      38874990        0
Bodies                           38874910        0
Senders                          38874990        0
Execution                        0               0
Translation                      0               0
HashState                        0               0
IntermediateHashes               0               0
AccountHistoryIndex              0               0
StorageHistoryIndex              0               0
LogIndex                         0               0
CallTraces                       0               0
TxLookup                         0               0
Finish                           0               0

prune distance:
blocks.v2: true, blocks=0, segments=0, indices=0
blocks.bor.v2: segments=0, indices=0
history.v3: false,  idx steps: 0.00, lastBlockInSnap=0, TxNums_Index(0,0)
sequence: EthTx=5826445992, NonCanonicalTx=0
in db: first header 38784000, last header 38874910, first body 38784000, last body 38874910

**Comment by wtdcode** [comment]
parlia rebuilding is supposed to be slow and taking long time. Try to wait a bit more.

**Comment by houkan** [comment]
so how long  the  [parlia] snapshots build, gather headers block=38800000 will takes.   i try to waiting more than 10 hours . and still stuck here.  nothing new.

[INFO] [06-08|17:11:46.316] [parlia] snapshots build, gather headers block=38800000
[INFO] [06-08|17:11:46.475] [parlia] snapshots build, gather headers block=38800000
[INFO] [06-08|17:11:46.618] [parlia] snapshots build, gather headers block=38800000

**Comment by rotarur** [comment]
I waited 1 week and it didn't move

**Comment by wtdcode** [comment]
If so, give the latest bsc-erigon version a try and see if it works.

**Comment by houkan** [comment]
If the solution is working, please give some feedback. Appreciate

**Comment by rotarur** [comment]
yes it works with the new version or erigon 1.2.10 and removing the `prohibit_new_downloads.lock` before upgrading

**Comment by houkan** [comment]
> yes it works with the new version or erigon 1.2.10 and removing the `prohibit_new_downloads.lock` before upgrading

thanks for your help..

**Comment by zzzckck** [comment]
fixed by https://github.com/node-real/bsc-erigon/pull/405, thx @wtdcode 's contribution.
pls upgrade your nodes to [v1.2.0+](https://github.com/node-real/bsc-erigon/releases/tag/v1.2.10)

**Comment by rotarur** [comment]
thank you guys for your help here
