### ISSUE TITLE
Can we sperate chaindata and ancient into 2 part ?

### ISSUE THREAD

**Issue by MhaiRuMhaiShee** [bnb-chain/bsc-snapshots#58]
it would be better for us to make a concurrent download in the same time. and ppl can choose which one they need

**Comment by Zorato** [comment]
That's really good idea 👍

**Comment by allada** [comment]
This is actually a really good idea... It might even be more useful for power users if the `ancient` folder was uploaded using `aws s3 sync` (ie: individual files) instead of compression, this way users could use `aws s3 sync` to bring in only the ancient folder that has changed from the local version (if one exists).

**Comment by JohnsonCaii** [comment]
Hi want to ask a question here: when will the size of ancient data folder get bigger?

**I found the explanation but I'm still haven't understand:**

Recent blocks, all state and accelerations structures are kept in a fast key-value store (LevelDB) as until now. This is meant to be run on top of an SSD as both disk IO performance is crucial.
Blocks and receipts that are older than a cutoff threshold (3 epochs) are moved out of LevelDB into a custom freezer database, that is backed by a handful of append-only flat files. Since the node rarely needs to read these data, and only ever appends to them, an HDD should be more than suitable to cover it.

---
Is the ancient data get bigger every time prune-state? or is it automatically move the hot data to cold data?

Thanks in advance!

**Comment by allada** [comment]
> Is the ancient data get bigger every time prune-state? or is it automatically move the hot data to cold data?
> 
> Thanks in advance!
`geth` moves data to ancient format in the background from the hot database.
